name: Run student_mark from py script
on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]  
jobs:
  student:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run a py script   
      run: python stdmark.py
